ensure sh shell available

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -3,15 +3,15 @@ name: Gradle Build & UT
 on: [push, pull_request, workflow_dispatch]
 
 jobs:
-#  build:
-#    uses: octopusden/octopus-base/.github/workflows/common-java-gradle-build.yml@v2.1.7
-#    with:
-#      flow-type: public
-#      java-version: '8'
+  #  build:
+  #    uses: octopusden/octopus-base/.github/workflows/common-java-gradle-build.yml@v2.1.7
+  #    with:
+  #      flow-type: public
+  #      java-version: '8'
 
   publish_and_test:
     runs-on: ubuntu-latest
-#    needs: build
+    #    needs: build
 
     steps:
       - name: Checkout
@@ -38,10 +38,20 @@ jobs:
       - name: Check .m2 repository contents
         run: ls -R ~/.m2/repository/org/octopusden/octopus || echo "Directory does not exist"
 
+      - name: Ensure sh shell is available
+        run: |
+          if ! command -v sh &> /dev/null; then
+            echo "sh could not be found, installing..."
+            sudo apt-get update
+            sudo apt-get install -y bash
+            sudo ln -s /bin/bash /bin/sh
+          else
+            echo "sh is available"
+          fi
+
       - name: Run tests
         env:
           LICENSE_REGISTRY_GIT_REPOSITORY: "https://github.com/aksetiyawan/license-registry-test.git"
           SUPPORTED_GROUPS: "org.octopusden.octopus"
         working-directory: ft
-        shell: bash
         run: ./gradlew test --tests org.octopusden.octopus.license.management.plugins.gradle.license.LicensePluginTest.testNodeSingleModule --debug --stacktrace --scan
