check sh availability

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -38,6 +38,9 @@ jobs:
       - name: Check .m2 repository contents
         run: ls -R ~/.m2/repository/org/octopusden/octopus || echo "Directory does not exist"
 
+      - name: Check for sh availability
+        run: which sh || echo "sh not found. Installing..." && sudo apt install sh
+
       - name: Run tests
         env:
           LICENSE_REGISTRY_GIT_REPOSITORY: "https://github.com/aksetiyawan/license-registry-test.git"
